import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import type { ParsedFile } from './code-gen/parser';

/**
 * Export project files as a ZIP download
 */
export async function exportProjectAsZip(
  files: ParsedFile[],
  projectName: string
) {
  const zip = new JSZip();
  const folder = zip.folder(projectName)!;

  for (const file of files) {
    folder.file(file.path.replace(/^\//, ''), file.content);
  }

  folder.file(
    'README.md',
    `# ${projectName}

Auto-generated by ASpark.

## Local Setup

\`\`\`bash
npm install
npm run dev
\`\`\`

## Deploy to Vercel

\`\`\`bash
npm i -g vercel
vercel
\`\`\`
`
  );

  const blob = await zip.generateAsync({ type: 'blob' });
  saveAs(blob, `${projectName}.zip`);
}
